GET http://localhost:3000/game/Medivia

###



POST http://localhost:3000/game/addgame
content-type: application/json

{
  "name":"It Takes Two",
  "age": 7,
  "typeOf": "Family Game"
}
###

GET http://localhost:3000/game

###
DELETE http://localhost:3000/game/15dc444c-2e92-49d2-b22f-4356a925278/delete

###


PUT http://localhost:3000/game/59b796f5-d1fc-4bf6-a9d1-27622833fceb
content-type: application/json

{
  "name": "It Takes Four"
}
